# Generated by Django 5.1.7 on 2025-03-24 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.CharField(max_length=255)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(db_column='track_id', on_delete=django.db.models.deletion.CASCADE, to='music.track')),
            ],
            options={
                'db_table': 'music_videos',
            },
        ),
        migrations.CreateModel(
            name='UserAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_albums',
            },
        ),
        migrations.CreateModel(
            name='SharedListeningInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('current_position', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('receiver', models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(db_column='track_id', on_delete=django.db.models.deletion.CASCADE, to='music.track')),
            ],
            options={
                'db_table': 'shared_listening_invitations',
                'indexes': [models.Index(fields=['sender', 'receiver'], name='shared_listening_idx')],
                'constraints': [models.UniqueConstraint(fields=('sender', 'receiver', 'track'), name='unique_invitation')],
            },
        ),
        migrations.CreateModel(
            name='UserAlbumTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_order', models.IntegerField()),
                ('track', models.ForeignKey(db_column='track_id', on_delete=django.db.models.deletion.CASCADE, to='music.track')),
                ('user_album', models.ForeignKey(db_column='user_album_id', on_delete=django.db.models.deletion.CASCADE, to='music.useralbum')),
            ],
            options={
                'db_table': 'user_album_tracks',
                'constraints': [models.UniqueConstraint(fields=('user_album', 'track_order'), name='unique_user_album_order'), models.CheckConstraint(condition=models.Q(('track_order__gte', 0)), name='track_order_non_negative')],
            },
        ),
    ]
