# Generated by Django 5.1.7 on 2025-03-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_musicvideo_useralbum_sharedlisteninginvitation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(blank=True, choices=[('pop', 'Pop'), ('rock', 'Rock'), ('jazz', 'Jazz')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
