# Generated by Django 5.1.7 on 2025-03-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_user_role_musicvideo_useralbum_message_and_more'),
        ('music', '0004_remove_artist_genre_track_genre_track_image'),
    ]

    operations = [
    ]
