# Generated by Django 5.1.7 on 2025-03-25 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_merge_20250325_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['sent_at']},
        ),
        migrations.RemoveConstraint(
            model_name='useralbumtrack',
            name='track_order_gte_0',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messages_sender_receiver_idx',
        ),
        migrations.AlterUniqueTogether(
            name='useralbumtrack',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='musicvideo',
            name='track',
            field=models.ForeignKey(db_column='track_id', on_delete=django.db.models.deletion.CASCADE, to='music.track'),
        ),
        migrations.AlterField(
            model_name='sharedlisteninginvitation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sharedlisteninginvitation',
            name='receiver',
            field=models.ForeignKey(db_column='receiver_id', on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedlisteninginvitation',
            name='sender',
            field=models.ForeignKey(db_column='sender_id', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharedlisteninginvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sharedlisteninginvitation',
            name='track',
            field=models.ForeignKey(db_column='track_id', on_delete=django.db.models.deletion.CASCADE, to='music.track'),
        ),
        migrations.AlterField(
            model_name='useralbum',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useralbumtrack',
            name='track',
            field=models.ForeignKey(db_column='track_id', on_delete=django.db.models.deletion.CASCADE, to='music.track'),
        ),
        migrations.AlterField(
            model_name='useralbumtrack',
            name='user_album',
            field=models.ForeignKey(db_column='user_album_id', on_delete=django.db.models.deletion.CASCADE, to='music.useralbum'),
        ),
        migrations.AddConstraint(
            model_name='useralbumtrack',
            constraint=models.UniqueConstraint(fields=('user_album', 'track_order'), name='unique_user_album_order'),
        ),
        migrations.AddConstraint(
            model_name='useralbumtrack',
            constraint=models.CheckConstraint(condition=models.Q(('track_order__gte', 0)), name='track_order_non_negative'),
        ),
    ]
